### ISSUE TITLE
InternationalCitiesStaticList

### ISSUE THREAD

**Issue by Pizzul** [robertogallea/laravel-codicefiscale#13]
Hi, I noticed that this code doesn't use the InternationalCitiesStaticList class but Italian List. In this case I get errors when checking the CodiceFiscale when I use foreign birth states. For example Z133 from Switzerland.

**Comment by robertogallea** [comment]
Hi Michele,
actually, the code doesn't use CityDecoderInterface implementations to
perform validation on the last 4 digits. It uses them only for decoding the
birthplace. Are you sure there is not any other problem in your codice
fiscale?

Could you please share (perhaps privately the fiscal number) so I could
perform some tests?

**Comment by Pizzul** [comment]
Ok, i fix in this way:

```
$cf = new CodiceFiscale(new InternationalCitiesStaticList());
$cf->parse($value);
```

So it also adds foreign nations (like Z133) and gives me success
