### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by giuseppeauteri** [robertogallea/laravel-codicefiscale#19]
Ciao Roberto, credo di aver trovato un bug nel tuo pacchetto. Alla riga 92 della classe CodiceFiscale istanzi il codice fiscale perdendo il "city-decoder" custom.

**Comment by robertogallea** [comment]
The issue has been fixed now, thank you!

**Comment by robertogallea** [comment]
A [test](https://github.com/robertogallea/laravel-codicefiscale/commit/4047cce82cf4404ba8de355527a6b0358e0d37b6#diff-7824f842eb85a3f12487314edc605c0d22f0d03ecf1ebeaf1be1a87b7e721e5bR119) was also added for that.
