### ISSUE TITLE
Installation failure laravel 8, PHP 7.4

### ISSUE THREAD

**Issue by i1990jain** [robertogallea/laravel-codicefiscale#20]
![image](https://user-images.githubusercontent.com/805570/118137801-e7b27300-b405-11eb-8e9c-3be249636959.png)

I am unable to install the package, as the installation fails with this error. I am using laravel 8 and PHP 7.4

**Comment by robertogallea** [comment]
Hi, is this a fresh package installation or an update? If it is an update, check you have a city-decoder class inside your `codicefiscale.php` config file

**Comment by i1990jain** [comment]
> Hi, is this a fresh package installation or an update? If it is an update, check you have a city-decoder class inside your `codicefiscale.php` config file

its a fresh package installation

**Comment by robertogallea** [comment]
Ok, tomorrow in the morning I'll check if something broke in the latest version. Thanks.

**Comment by robertogallea** [comment]
Hi,
I created a brand new L8 application using php7.4 and cannot reproduce your issue:

```
$ php -v
PHP 7.4.18 (cli) (built: May  3 2021 11:26:48) ( NTS )

$ laravel new test-cf
Installing laravel/laravel (v8.5.17)

...


$ composer require robertogallea/laravel-codicefiscale
Using version ^1.6 for robertogallea/laravel-codicefiscale
./composer.json has been updated
Running composer update robertogallea/laravel-codicefiscale
Loading composer repositories with package information
Updating dependencies
Lock file operations: 1 install, 0 updates, 0 removals
  - Locking robertogallea/laravel-codicefiscale (1.6.1)
Writing lock file
Installing dependencies from lock file (including require-dev)
Package operations: 1 install, 0 updates, 0 removals
  - Downloading robertogallea/laravel-codicefiscale (1.6.1)
  - Installing robertogallea/laravel-codicefiscale (1.6.1): Extracting archive

...

Discovered Package: robertogallea/laravel-codicefiscale
Package manifest generated successfully.

```

Could you please provide more details?
