### ISSUE TITLE
Error su un codice

### ISSUE THREAD

**Issue by FrankFlow** [robertogallea/laravel-codicefiscale#26]
Su questo CF **svrdvd73s26b665l**
restituisce il seguente errore

`[2021-07-19 16:07:09] production.ERROR: Undefined index: B665 {"exception":"[object] (ErrorException(code: 0): Undefined index: B665 at .../vendor/robertogallea/laravel-codicefiscale/src/CodiceFiscale.php:189)
`

**Comment by FrankFlow** [comment]
Il comune è Muggia (Trieste)

**Comment by robertogallea** [comment]
Il comune B665 mi risulta essere CAPODISTRIA, cessato (diventato città slovena).

Muggia risulta essere F795 (già censito)

Puoi verificare?

**Comment by FrankFlow** [comment]
Verifico. Ti aggiorno. Grazie.

**Comment by FrankFlow** [comment]
In realtà non è Muggia. Ho sbagliato io. Quella era la città di residenza. Quindi comunico che B665 è un comune non più italiano. Grazie Roberto.

**Comment by FrankFlow** [comment]
Mi aggiorni sulla questione del file di configurazione se è gestito anche quando utilizzi le regole di validazione di Laravel? Grazie

**Comment by robertogallea** [comment]
Confermato, il validator usa il servizio registrato dal provider e rispetta quanto definito in configurazione.

**Comment by FrankFlow** [comment]
Ok, grazie.

**Comment by Procionegobbo** [comment]
Un suggerimento: non si potrebbe aggiungere un'exception specifica per questo tipo di errore? Qualcosa tipo `BAD_CITY_CODE`.
In modo da evitare errori usando una FormRequest

**Comment by robertogallea** [comment]
A quale errore ti riferisci? Un codice fiscale recante un comune cessato credo resti comunque valido.

**Comment by Procionegobbo** [comment]
```
<?php

use robertogallea\LaravelCodiceFiscale\CodiceFiscale;


$cf = new CodiceFiscale();
$result = $cf->parse('LNEGLI94D20A009X');

echo $cf->getError();
```

`Undefined array key "A009" in /Users/federicomaiorini/dev/FITPRIME/fitprime.test/vendor/robertogallea/laravel-codicefiscale/src/CodiceFiscale.php on line 189`

**Comment by robertogallea** [comment]
La versione 1.8.1 è stata rilasciata, e contiene l'errore di validazione sulla codice comune mancante, mappato su `MISSING_CITY_CODE`. 

Grazie per il contributo.

**Comment by Procionegobbo** [comment]
Grazie a te per questo package.

**Comment by robertogallea** [comment]
Se ti è utile e vuoi supportarlo puoi fare anche una piccola sponsorizzazione, giusto per farmi capire che il mio lavoro è utile ed essere da motivazione :)
