### ISSUE TITLE
ISTAT bloccato

### ISSUE THREAD

**Issue by FrankFlow** [robertogallea/laravel-codicefiscale#39]
Segnalo un blocco del sito dell'istat per il check CF  a causa di  rischio attacchi informatici.

![Schermata 2021-12-14 alle 11 34 46](https://user-images.githubusercontent.com/7053026/145982530-19bd1fa1-595a-4503-ab2e-07e7501e7914.png)

**Comment by robertogallea** [comment]
Grazie, purtroppo questo è un rischio da tenere in conto...

**Comment by FrankFlow** [comment]
Grazie a te,

comunque abbiamo risolto con il config file che richiama la static-list italiana
Il 14 dic 2021, 11:48 +0100, Roberto Gallea ***@***.***>, ha scritto:
