### ISSUE TITLE
fake() -  InvalidArgumentException: Unknown format "codiceFiscale"

### ISSUE THREAD

**Issue by eleftrik** [robertogallea/laravel-codicefiscale#65]
* robertogallea/laravel-codicefiscale version `2.0.0`
* Laravel 11.x application

Everything works as expected when using `$this->faker->codiceFiscale()` (for example, in a factory).

However, when using `fake()->codiceFiscale()`, I get this error: `InvalidArgumentException: Unknown format "codiceFiscale"`.

I was able to fix it by adding this line to a service provider (e.g. `AppServiceProvider.php`):

`fake()->addProvider(app(CodiceFiscaleFakerProvider::class));`

I didn't open a PR because the example in README.md uses `fake()`, so it could only be a problem related to my application. 

Thanks

**Comment by robertogallea** [comment]
You were right and the readme was wrong ;)
Thank you!

**Comment by robertogallea** [comment]
Fixed in [v2.0.1](https://github.com/robertogallea/laravel-codicefiscale/commit/73dabd5b9dc6a4aad10c05f47df6021720fb6fa7)

**Comment by eleftrik** [comment]
Thanks @robertogallea for this wonderful package!
