### ISSUE TITLE
CheckForWrongCode

### ISSUE THREAD

**Issue by makroxyz** [robertogallea/laravel-codicefiscale#7]
Why CheckForWrongCode isn't in private checks attribute in CodiceFiscale.php?

**Comment by robertogallea** [comment]
I cannot remember any valid reasons for that. Perhaps I just forgot to include it.

**Comment by makroxyz** [comment]
I made a pull request with this and another fix, could you have a look please?

**Comment by robertogallea** [comment]
Sure, I asked you to fix CircleCI warning before merging, thanks!
